// {

// "accept_terms_and_conditions": "Accept Terms And Conditions",
// "account_verified": "Your account verified successfully",
// "activate": "Activate",
// "add_new_address": "Add new address",
// "add_to_cart": "Add to cart",
// "added_successfully": "Added successfully",
// "added_to_favorite": "Added to favorite successfully",
// "address": "Address",
// "address_details": "Address details",
// "address_name": "Address name",
// "addresses": "Addresses",
// "agree": "Agree",
// "agree_terms_and_services": "You must agree to the terms and conditions.",
// "air_conditioner_type": "Air conditioner type",
// "all_centers": "All centers",
// "all_stores": "All stores",
// "allow_notifications": "Allow the application to receive notifications?",
// "apply": "Apply",
// "area": "Area",
// "at_least_10_char": "It must be at least 10 numbers",
// "at_least_4_char": "It must be at least 4 characters",
// "at_least_7_char": "It must be at least 7 characters",
// "at_least_7_num": "It must be at least 7 numbers",
// "at_least_one_product": "At least one product must be selected",
// "at_most_15_char": "It must be at most 15 characters",
// "at_most_15_num": "It must be at most 15 numbers",
// "at_most_300_char": "It must be at most 300 characters",
// "at_most_75_char": "It must be at most 75 characters",
// "available_payment_methods": "Available payment methods",
// "bank_accounts": "Bank accounts",
// "mukyfy_driver": "mukyfy_driver",
// "best_product_offers": "Best product offers",
// "bill": "Bill",
// "camera": "Camera",
// "cancel": "Cancel",
// "cancel_order": "Cancel Order",
// "cancel_reason": "Cancel reason",
// "cart": "Cart",
// "catalog": "Catalog",
// "category": "Category",
// "center": "Center",
// "centers": "Centers",
// "change_lang": "Change Language",
// "change_order_status": "Order status changed successfully",
// "chat_now": "Chat now",
// "choose_address_type": "Choose address type",
// "choose_air_conditioner_type": "Choose air conditioner type",
// "choose_bank_account": "Choose bank account",
// "choose_brand": "Choose brand you looking for",
// "choose_category": "Choose category",
// "choose_complaint_type": "Choose complaint type",
// "choose_file": "Choose file",
// "choose_lang_to_continue": "Please Choose Your Preferred Language",
// "choose_payment_method": "Choose payment method",
// "choose_photo_from": "Choose photo from",
// "city": "City",
// "cod": "Cash on delivery",
// "code_sent_to": "Code sent to",
// "code_sent_within": "Code sent with in",
// "comments": "Comments",
// "complaint": "Complaint",
// "complete_order": "Complete order",
// "complete_shopping": "Complete shopping",
// "confirm": "Confirm",
// "confirm_new_password": "Confirm New Password",
// "confirm_password": "Confirm Password",
// "contact_us": "Contact Us",
// "contact_us_2": "Contact Us",
// "contact_with_whats": "Contact via WhatsApp",
// "contactus_hint": "We will contact you after we receive your message or complaint in less than 24 hours",
// "continue_btn": "Continue",
// "cost": "Cost",
// "country": "Country",
// "coupon_value": "Coupon value",
// "create_new_account": "Create New Account",
// "create_new_account_2": "Create New Account",
// "delete": "Delete",
// "delete_all": "Delete all",
// "delete_item_from_cart": "Do you want to delete this card item?",
// "deleted_successfully": "Deleted successfully",
// "delivered": "Delivered",
// "delivery_charge": "Delivery charge",
// "deposit_amount": "Deposit amount",
// "depositor_name": "Depositor name",
// "detect_locations": "Allow the app to detect your location?",
// "discount": "discount",
// "discount_coupon": "Discount coupon",
// "discount_value": "Discount value",
// "do_not_have_account_q": "Don't Have Account?",
// "done": "Done",
// "done_service": "Done",
// "edit_password": "Edit password",
// "edited_successfully": "Edited successfully",
// "email": "Email",
// "enter_deposit_amount": "Enter deposit amount",
// "enter_depositor_name": "Enter depositor name",
// "enter_message": "enter message",
// "enter_mobile": "Enter mobile",
// "enter_name_building": "Enter name/number building",
// "enter_name_street": "Enter name/number street ",
// "enter_new_password": "Enter new password.",
// "enter_the_code": "Enter the code",
// "enter_title": "Enter title",
// "enter_valid_number": "Enter valid number",
// "enter_your_full_name": "Enter your full name",
// "filter_title": "Filter",
// "first_name": "First name",
// "forget_password": "Forget Password ?",
// "forget_password_q": "Forget Password?",
// "free_cash_charge": "Free cash charge",
// "free_delivery_charge": "Free delivery charge",
// "from": "From",
// "gallary": "Gallary",
// "guest": "Guest",
// "have_account_q": "Have Account?",

// "how_can_we_help_you": "How can we help you ?",
// "inspection_fees": "Inspection fees",
// "invoice": "Invoice",
// "invoice1": "Invoice order number ",
// "invoice_downloaded": "The invoice has been downloaded to the device",
// "item_updated_successfully": "item updated successfully",
// "lang": "Language",
// "last_name": "Last name",
// "location_on_map": "Location on map",
// "login": "Login",
// "logout": "Logout",
// "main_address": "Main address",
// "main_categories": "Main Categories",
// "minimum_return": "Minimum return quantity is 1 of the product",
// "mobile": "Mobile",
// "mobile_num": "Mobile Number",
// "more_requested_products": "More requested products",
// "most_rated": "Top rated",
// "most_selling": "Most selling",
// "my_account": "My Account",
// "my_addresses": "My addresses",
// "my_basic_personal_information": "My basic personal information",
// "my_fav": "My Favourite",
// "my_orders": "My Orders",
// "my_personal_info": "My personal information",
// "name": "Name",
// "nearest_landmarks": "Nearest landmarks",
// "new_password": "New Password",
// "newly_added": "Newly added",
// "next_btn": "Next",
// "no": "No",
// "no_data": "There are no data",

// "notes": "Notes",
// "notes_in_shipping": "Notes in shipping",
// "notifications": "Notifications",
// "offer_discount": "Offer discount",
// "offers": "Offers",
// "old_password": "Old Password",
// "on_the_date": "On the date",
// "online": "Online",
// "open_location_settings": "Open Location Settings",
// "open_map": "Open In Maps",
// "operation_details": "Operation details",
// "operation_number": "Operation number",
// "order": "Order",
// "order_details": "Order Details",
// "order_history": "Order history",
// "order_num": "Order number",
// "order_product": "Order Product",
// "order_refund": "The order has been refund",
// "order_return": "Order return",
// "order_status": "Order status",
// "our_most_popular_stores": "Our most popular stores",
// "password": "Password",
// "password_not_match": "Password does not match",
// "password_validations": "Password must contain an uppercase, lowercase, numbers, and special character",
// "pay_now": "Pay now",
// "payment": "Payment",
// "payment_success": "Payment success",
// "payment_success_hint": "Payment has been made successfully and invoice details have been sent to the email",
// "phone": "Phone number",
// "phone_changed_successfully": "Phone changed successfully",
// "please_enter_password": "Please enter a password.",
// "please_enter_phone_number": "Please enter phone number.",
// "please_enter_the_confirm_password": "Please enter the confirm password.",
// "please_enter_valid_email": "Please enter a valid email",
// "please_enter_valid_message": "Please enter a valid message",
// "please_enter_valid_name": "Please enter a valid name",
// "please_enter_valid_phone_number": "Please enter valid phone number.",
// "please_login": "Please Login",
// "please_login_2": "Please Login",
// "plz_choose_address": "Please choose address",
// "plz_enter_mobile_to_reset_password": "Please enter your mobile number to reset password",
// "plz_enter_new_password": "Please enter new password",
// "plz_enter_new_phone": "Please enter new phone",
// "plz_enter_rate": "Please enter rate",
// "plz_enter_your_data": "Please enter your complete personal data",
// "price": "Price",
// "price_from_high_to_low": "Price from high to low",
// "price_from_low_to_high": "Price from low to high",
// "price_starts_from": "Price starts from",
// "primary": "Primary",
// "privacy_policy": "Privacy Policy",
// "problem_description": "Problem description",
// "product_details": "Product Details",
// "product_is_being_returned": "Product is being returned",
// "product_rate": "Product Rate",
// "product_return": "Product return",
// "products_num_in_cart": "Products number in cart",
// "products_orders": "Products requests",
// "products_total": "Products total",
// "profile": "Profile",
// "profile_updated": "Profile updated",
// "promo_code_discount": "Promo code discount",
// "quantity": "Quantity",
// "quantity_returned": "Only this quantity can be returned",
// "rate_product": "Rate product",
// "rate_product_and_write_comment": "Rate the product and write comment",
// "rate_service": "Rate service",
// "rate_service_and_write_comment": "Rate the service and write comment",
// "rates": "Rates",
// "recent_search_results": "Recent search results",
// "refund_total": "Refund total",
// "refunds": "Refunds",
// "register": "Register",
// "related_products": "Related Products",
// "remain_to_pay": "Remain to pay",
// "remove_favorite": "Removed from favourites Successfully",
// "request_service": "Request service",
// "required": "required",
// "required_field": "required",
// "resend_code": "Resend Code",
// "reset": "Reset",
// "return_order": "Return order",
// "return_policy": "Return policy",
// "return_reason": "Return reason",
// "return_request_denied": "Return request denied",
// "sar": "sar",
// "sar2": "sar",
// "sar3": "sar",
// "save": "Save",
// "search_title": "Search",
// "select": "Select",
// "select_all": "Select all",
// "select_the_type_of_warranty": "Select the type of warranty",
// "select_your_location": "Select your location",
// "send": "Send",
// "send_rate": "Send Rate",
// "sent_successfully": "Sent successfully",
// "service_cost": "Service cost",
// "service_desc": "Service description",
// "service_details": "Service Details",
// "service_num": "Service order number",
// "service_rate": "Service Rate",
// "service_request": "Service request",
// "services_orders": "Services requests",
// "share_message": "I invite you to purchase this product from the My mukyfy_driver app",
// "shipping": "Shipping",
// "shipping_address": "Shipping address",
// "show_more": "Show More",
// "skip_now": "Skip now",
// "sort_by": "Sort by",
// "store": "Store",
// "stores": "Stores",
// "suggestion": "Suggestion",
// "tax_included": "Tax included",
// "tax_value": "Tax value",
// "taxes": "Tax Value",
// "terms_and_conditions": "Terms And Conditions",
// "the_date_to_be_served": "The date to be served",
// "the_most_famous_centers": "The most famous centers",
// "there_is_no_brands": "There is no brands",
// "there_is_no_categories": "There is no categories",
// "there_is_no_cities": "There is no cities",
// "there_is_no_countries": "There is no countries",
// "there_is_no_states": "There is no areas",
// "there_is_no_subCategories": "there is no types",
// "to": "To",
// "total": "Total",
// "total_before_discount": "Total before discount",
// "total_comments": "Total comments",
// "total_cost": "Total cost",
// "trademarks": "Trademarks",
// "transactions_on_wallet": "Transactions On Wallet",
// "unverified": "please verify your account",
// "update": "Update",
// "update_account_data": "Update my account information",
// "update_picture": "Update picture",
// "use_wallet": "Use wallet",
// "user_inactive": "Your account has been deactivated, please return to the admin",
// "user_name": "User Name",
// "valid_discount_coupon": "Valid discount coupon",
// "verify_phone_number": "Verify phone number",
// "view_more": "View More",
// "wallet": "Wallet",
// "warranties_total": "Warranties total",
// "welcome": "Welcome",
// "what_are_you_looking_for": "what are you looking for ?",
// "write_cancel_reason": "Write the reason for cancellation",
// "write_comment": "Write Comment",
// "yes": "Yes",
// "you_already_use_this_phone_number": "You already use this phone number",
// "you_can_see_this_product": "You can see this product",
// "you_can_see_this_service": "You can see this service in mukyfy_driver App",
// "you_logged_as": "you logged in as a",
// "you_must_choose_country": "You must choose a country",
// "your_place": "Your place on the map",
// "mukyfy": "mukyfy",
// "experience_with_development": "Experience with development",
// "welcome_again": "welcome again",
// "please_log_in": "Please log in",
// "personal_page": "personal page",
// "personal_driver_information_with_the_possibility_of_modification": "Personal driver information with the possibility of modification",
// "notification": "notification",
// "a_new_request_a_transfer_request_or_a_renewal_request": "A new request, a transfer request, or a renewal request",
// "delivery_orders": "Delivery orders",
// "all_about_delivery_orders": "All about delivery orders, details",
// "all_about_delivered_orders": "All about finished orders, details",
// "settings": "Settings",
// "notification_new_order_transfer_cancel": "New order, transfer order, or cancel order",
// "settings_change_language_logout": "change language, log out",
// "information": "informations",
// "about_the_application_and_the_developer_customer_service_usage_policy": "About the application and the developer, customer service, usage policy",
// "personal_account_information": "personal account information",
// "driver_name": "driver name",
// "driver_credit": "driver credit",
// "collected_orders": "collected orders",
// "rs": "RS",
// "total_number_of_orders": "Total Order Numbers",
// "order_number": "order number",
// "required_salary": "required salary",
// "refuse_order": "Refuse Order",
// "accept_order": "Accept Order",
// "recieve_order": "recieve order",
// "diredctions": "diredctions",
// "order_tracking": "order tracking",
// "arrival_at": "arrival at",
// "request_accepted": "Request accepted",
// "order_has_been_delivered": "The order has been delivered",
// "request_has_been_returned": "The request has been returned",
// "order_delivered": " Order Delivered",
// "it_was_received": "received",
// "it_was_retrieved": "retrieved",
// "refuse_receiving": "Client Refused",
// "back": "Back",
// "enter_text": "enter text",
// "accept": "Accept",
// "accepted": "Accepted",
// "ad_details": "Advertisement Details",
// "ad_number": "Advertisement number",
// "add_advertisement": "Add Advertisement",
// "add_type": "Advertisement Type",
// "added_by": "Added By",
// "advertising_data": "Advertising Data",
// "agents": "Agents",
// "agricultural": "Agricultural",
// "all": "All",
// "annual": "annual",
// "app_name": "Qimm",
// "architectural_style": "Architectural style",
// "archive": "Archive",
// "archived_ads": "Archived",
// "archived_successfully": "Archived successfully",
// "are_you_sure_delete_account": "Are you sure you want to delete the account?",
// "area_in_square_meters": "Area is in square meters",
// "at_least_3_char": "It must be at least 3 characters",
// "at_least_4_num": "It must be at least 4 numbers",
// "at_most_10_num": "It must be at most 10 numbers",
// "at_most_6_number": "It must be at most 6 numbers",
// "authorization_attachment": "Authorization Attachment",
// "authorization_number": "Authorization number",
// "available": "Available",
// "bathroom": "Bathroom",
// "bedrooms": "Bedrooms",
// "brief_description_advertisement": "Advertisement Brief description",
// "building_rental": "Building Rental",
// "building_sale": "Building Sale",
// "car_park": "Car park",
// "change_language": "Change Language",
// "change_languge": "Change Languge",
// "change_password": "Change Password",
// "choose_another_location": "Choose another location",
// "choose_date_time_tour": "Choose date and time of the tour",
// "choose_user_type": "Choose User Type",
// "code_actived": "Code has been activated",
// "commercial": "Commercial",
// "communicate_with_advertiser": "Contact with the advertiser",
// "complete_ad": "complete Ad",
// "complete_advertisement_data": "Complete advertisement Data",
// "construction_year": "Construction year",
// "contact_advertiser_fill_information": "To contact the advertiser, please fill in the following information",
// "contact_us_hint": "Are you facing a problem or have a question?",
// "conversational_requests": "Conversational Requests",
// "conversations": "Chat",
// "cooling": "Cooling",
// "daily": "daily",
// "date_of_publication": "Date of publication",
// "delete_account": "Delete Account",
// "detect_add_type": "Choose the advertisement type ,you need to add",
// "dhimma_message": "Dhimma Message",
// "draft": "Drafts",
// "edit": "Edit",
// "edit_ad": "Edit advertisement",
// "edit_address": "You can edit your address ",
// "edit_profile": "You can edit your account here",
// "elevator": "Elevator",
// "enter_address_city": "Enter an address, neighborhood, city or zip code",
// "enter_next_data_to_sign_up": "Please enter next data to sign up",
// "enter_valid_year": "Enter valid year",
// "error_try_again": "Something went wrong please try again",
// "expiration_period": "Expiration period",
// "expiration_period_in_month": "Package Validity in Months",
// "expired_at": "Expire Date",
// "external_features": "External features",
// "facts_and_features": "Facts and Features",
// "favorite": "Favorite",
// "filter": "filter",
// "finance": "Finance",
// "for_rent": "For Rent",
// "for_sale": "For Sale",
// "gallery": "Gallery",
// "here": "here",
// "home_address": "Address",
// "home_details": "Details",
// "home_photos": "Photos",
// "home_type": "Type",
// "homeowners_association_fee": "Owners Association Fee",
// "house_owner": "Building owner",
// "job": "Job",
// "kitchen": "Kitchen",
// "living_rooms": "living rooms",
// "location_has_been_denied": "The location has been denied",
// "max_num_of_properties": "Max number of properties",
// "max_num_of_users": "Max number of users",
// "means_of_comfort": "Means of comfort",
// "message": "Message",
// "message_sent": "Message sent successfully",
// "minimum_one_photo_maximum_thirty_photos": "A minimum of one photo, a maximum of 30 photos",
// "monthly": "monthly",
// "more": "More",
// "more_data": "More data",
// "must_select_location": "You must choose your location from the map",
// "my_address": "My Address",
// "my_ads": "My ads",
// "my_interests": "My Interests",
// "neighbor": "Neighbor",
// "no_archived_ads": "There are no archived ads",
// "no_sold_ads": "There are no sold ads",
// "not_available": "Not available",
// "num_of_ads": "Number of Ads",
// "number_months": "Number of Months",
// "number_of_bathroom": "Number of bathroom",
// "number_of_bedrooms": "Number of bedrooms",
// "number_of_living_rooms": "Number of living rooms",
// "number_of_rooms": "Number of rooms",
// "number_of_toilets": "Number of toilets",
// "office_employee": "Office Employee",
// "ok": "Ok",
// "other_services": "Other services",
// "package_details": "Package details",
// "packages": "Packages",
// "password_changed": "Password has been changed",
// "payment_type": "Payment type",
// "personal_data": "Personal data",
// "post_successfully": "post successfully",
// "problem_downloading_image": "There is a problem downloading the image",
// "properties_for_rent": "Ads for rent",
// "properties_for_sale": "Ads for sale",
// "property_type": "Property type",
// "publish": "Publish",
// "publish_the_ad": "Publish",
// "publish_to_admin": "Send to admin",
// "publish_to_admin_success": "Publish to admin successfully",
// "read_more": "Read more",
// "real": "RAS",
// "reason_for_rejection": "Reason for rejection",
// "refuse_tour_request": "Refuse tour request",
// "register_info": "You can create an account in easy steps, just register a new one and surround the road, then enjoy the features that it offers you",
// "register_success": "You have been successfully registered and an activation code has been sent to your mobile number",
// "reject": "Reject",
// "rejected": "Rejected",
// "remember_me": "Remember me",
// "rent": "Rent",
// "rental_duration": "Rental Duration",
// "rental_type": "rental type",
// "request_sent_to_office": "Request has been sent to the office",
// "request_tour": "Request a tour",
// "residential": "Residential",
// "rooms": "Rooms",
// "rooms_1": "Room",
// "salary": "Salary",
// "sale": "Sale",
// "saved": "Save Ad",
// "saved_searches": "Saved searches",
// "search_for_an_agent": "Search for an agent",
// "sections_of_the_house": "Sections",
// "share": "Share",
// "sharing": "Sharing",
// "should_4_num": "It must be 4 numbers",
// "similar_ads": "Similar ads",
// "skip": "Skip",
// "sold": "Sold",
// "sold_ads": "Sold",
// "square_meters": "Square meters",
// "state": "State",
// "subscribe": " Subscribe",
// "subscribe_at": "Subscription Date",
// "subscribe_successfully": "Subscribe successfully",
// "subscriber_packages": "Subscriber Packages",
// "subscription_rules": "You can subscribe to another package",
// "the_price_house_riyals": "The price",
// "time": "Time",
// "total_area_of_unit": "Total area of the unit",
// "tour_date": "Tour date",
// "tour_management": "Tour management",
// "tour_time": "Tour time",
// "unsubscribe": "Unsubscribe",
// "use_current_location": "Use the current location",
// "user": "User",
// "verification_code_sent": "Verification code has been sent to your phone",
// "verification_details": "The account confirmation code has been sent to your mobile number. Please check and include it in the following fields",
// "write_your_message_here": "Write your message here",
// "year_of_construction": "Year of construction",
// "you_should_select_type": "You should select type",
// "your_ad_created": "Your ad has been created",
// "your_ad_edited": "your ad has been edited",
// "your_request_sent": "Your request has been sent",
// "zoon": "zoon"
// }